# Generated by Django 4.2.3 on 2023-07-13 01:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoCinematográfico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre del Tipo Cinematográfico')),
            ],
            options={
                'verbose_name': 'Tipo Cinematográfico',
                'verbose_name_plural': 'Tipos Cinematográficos',
            },
        ),
        migrations.CreateModel(
            name='ObraCinematográfica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre Obra')),
                ('fecha', models.CharField(max_length=10, verbose_name='Año de estreno')),
                ('descripcion', models.TextField(max_length=1000, verbose_name='Descripción')),
                ('tipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='series_peliculas.tipocinematográfico', verbose_name='Tipo Cinematográfico')),
            ],
            options={
                'verbose_name': 'Obra Cinematográfica',
                'verbose_name_plural': 'Obras Cinematográficas',
            },
        ),
    ]
