# Generated by Django 4.2.3 on 2023-07-12 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Juegos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='juego',
            name='descripcion',
            field=models.TextField(max_length=1000),
        ),
    ]
