# Generated by Django 4.2.3 on 2023-07-11 23:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoLiteratura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comic_libro', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Tipo de literatura',
                'verbose_name_plural': 'Tipos de literaturas',
            },
        ),
        migrations.CreateModel(
            name='Libreria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('autor', models.CharField(max_length=50)),
                ('descripcion', models.TextField(max_length=500)),
                ('tipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Libreria.tipoliteratura')),
            ],
        ),
    ]
